Task/weather in circle
Aydar710/Weather pull request #1
Opened 2018-12-03 22:03 UTC by Aydar710

2018-12-04 11:38 UTC, Aydar710 commented
![photo_2018-12-04_14-38-30](https://user-images.githubusercontent.com/32329290/49439521-50777900-f7d2-11e8-9273-572c5dc54a19.jpg)
![photo_2018-12-04_14-38-35](https://user-images.githubusercontent.com/32329290/49439522-50777900-f7d2-11e8-961c-02f94dc9e818.jpg)

2018-12-04 21:29 UTC, NailShaykhrazievItis requested changes

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/Constants.kt
> +interface Constants {
сделай просто класс, без всего вот этого, лучше скрин скину

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/Retrofit.kt
> +                var request = chain.request()
лучше выносит для читабельности

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/Retrofit.kt
> +    companion object {
companion  здесь не решение. Совсем костыльно выглядит

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/WeatherAdapter.kt
> +        holder.txtTemp.text = listElement.main?.temp.toString()
не должен адаптер отвечать за биндинг данных, для специально был создан отдельный паттер в программирование Holder, вот пусть он и занимается биндингом

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/activities/MainActivity.kt
> +        checkLocationPermission()
Ты проверил пермишены, но у тебя код не должен пытаться получить локацию если их не дали, а у тебя сейчас без разницы есть пермишены или нет

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/activities/WeatherDetailsActivity.kt
> +                    val element: WeatherResponse.ListElement = list[position]
ну в принципе можно, но лучше б было б это локально сохранять или сразу передавать на экран, или не ходить за всеми в сеть. Ты мог передать сюда айдишник/имя/координаты конкретного города и потом сходить на отдельный эндпоинт за ним одним, а не качать все 20 заново

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/models/Clouds.kt
> +class Clouds {
переделай все классы в датаклассы, ты можешь некоторые спокойно объединять в одном файле

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/repository/WeatherRepository.kt
> +class WeatherRepository(val weatherApi: WeatherApi) {
сильно

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/repository/WeatherRepository.kt
> +        return weatherApi.getCitiesInCycle(coord.lat.toString(), coord.lon.toString(), "20")
"20" в константу

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/repository/WeatherRepository.kt
> +        kelvin?.let {
тут ты мог написать экстеншен для даббла, если не понятно будет пиши в лс

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/aydar/emptyweather/repository/WeatherRepository.kt
> +        var list: ArrayList<WeatherResponse.ListElement> = ArrayList()
а зачем

2018-12-04 21:29 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_weather_details.xml
> +        android:id="@+id/txt_details_country"
пускай будет txt

2018-12-05 19:49 UTC, NailShaykhrazievItis approved these changes

2018-12-10 20:07 UTC, closed without merging